### ISSUE TITLE
There was an error when I loaded the driver

### ISSUE THREAD

**Issue by shincehor** [djackreuter/lvlchg_client#1]
There was an error when I loaded the driver

sc start lvlchg
[SC] StartService fail 577:
Windows cannot verify the digital signature of this file. A piece of software or hardware has recently changed, a missigned or corrupted file may be installed, or the installed file may be malware from an unknown source

**Comment by djackreuter** [comment]
The driver is not signed, so you likley need to enable testsigning on the machine to load the driver. Run the following in an elevated command prompt and reboot. Loading the driver should work after that.
```bcdedit /set testsigning on```
